# Generated by Django 5.1.4 on 2024-12-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElectricityConnectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                ("aadhar_number", models.IntegerField(unique=True)),
                ("aadhar_card", models.FileField(upload_to="aadgar_cards/")),
                ("subject", models.TextField()),
            ],
        ),
    ]
