# Generated by Django 5.1.4 on 2024-12-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricityconnectionrequest",
            name="aadhar_card",
            field=models.FileField(upload_to="aadhar_cards/"),
        ),
    ]
